### PR TITLE
Make the Site Prettier

### PR DESCRIPTION
**Pull request by belph**
This PR makes a couple of tweaks to make the Pyret website less 'standard-bootstrap'-y. I tried playing with the color scheme, but, with the colors in the main logo, grey really seems to be the best option.

A demo of the site with the changes can be found [here](http://belph.github.io/pyret-hip/).

### CODE REVIEW

**Comment by mkolosick** [comment]
Have you looked at this from a mobile device or simulation of one? There seem to be a few issues with overrunning box margins.

**Comment by belph** [comment]
@mkolosick Those are problems which need to be fixed, but, on my phone, [`pyret.org`](http://pyret.org) has the same issues (unless you're referring to something I'm missing).

**Comment by mkolosick** [comment]
Ah, I see. pyret.org has the same issue for me as well.

**Comment by blerner** [comment]
Is it possible to have the title-bar (the small logo and the other links) not scroll offscreen?  Otherwise, we might just ditch the small logo and make the bigger one bigger yet.

**Comment by belph** [comment]
Done. The preview should be updated as well.

**Comment by jpolitz** [comment]
This seems like an improvement to me.  I'm happy to merge unless @shriram or @blerner object.

**Comment by belph** [comment]
(Note: the preview has messed up CSS for pages other than the homepage due to relative `src` paths, etc. etc...running a preview with `raco frog` properly renders all pages)

**Comment by jpolitz** [comment]
Pushed.

**Pull request merged**
