### PR TITLE
Preparing to deprecate the old style of method

### PR DESCRIPTION
**Pull request by sorawee**

### CODE REVIEW

**Comment by blerner** [comment]
Why do it this way? You can keep the other syntax, but *prefix* it with `method` before the method name.

**Comment by sorawee** [comment]
Sure. Changed.

**Comment by sorawee** [comment]
Ughh, I just realized the original purpose of the PR. I would like to discourage the use of the old method syntax _now_, so that Pyret users don't write in the way that the code would break when horizon lands. On the other hand, the new method syntax doesn't exist yet, so I don't want to use it. My original PR is a compromise of these two. It works in all branches.

Anyway, since I changed it to a new method syntax, please don't merge this yet because currently the syntax doesn't exist in the CPO.

**Comment by blerner** [comment]
The problem with the `name: method()...` syntax is it requires introducing the notion of anonymous methods, which is even more subtle than anonymous lambdas. I don't want to introduce that concept here!

**Comment by sorawee** [comment]
Fixed already by https://github.com/brownplt/pyret.org/commit/838ce1835733f76d439a81e4ad3637ae345d86ae and https://github.com/brownplt/pyret.org/commit/648e181688d8ce751d564e4087404ddc49afa3f1

**Pull request closed without merging**
